name: Build and Test GPU

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build-and-test-cuda-cli:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'

      - name: Build SCAMP with CUDA
        shell: bash
        run: |
          set -e
          cd $GITHUB_WORKSPACE
          mkdir build && cd build
          cmake -DFORCE_CUDA=1 ..
          cmake --build . --config Release --parallel 2
          
      - name: Basic CUDA Tests SCAMP
        shell: bash
        run: |
          set -e
          cd $GITHUB_WORKSPACE/test
          ./run_tests.sh ../build/SCAMP /dev/null
          
      - name: Extended Tests SCAMP
        shell: bash
        run: |
          set -e
          cd $GITHUB_WORKSPACE/test
          python3 ./run_tests.py --executable "../build/SCAMP"
