# This is a basic workflow to help you get started with Actions

name: Ubuntu Cuda Build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        compiler: [g++, clang++, msvc]
        exclude:
          os: ubuntu-latest
          compiler: msvc
        exclude:
          os: macos-latest
          compiler: msvc
        exclude:
          os: windows-latest
          compiler: g++
        exclude:
          os: windows-latest
          compiler: clang++

    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - uses: Jimver/cuda-toolkit@v0.2.5
        id: cuda-toolkit
        with:
          cuda: '11.5.1'

      # Runs a single command using the runners shell
      - name: Build SCAMP
          run: |
          set -e
          cd $GITHUB_WORKSPACE
          mkdir build && cd build
          if: matrix.os != 'windows-latest'
            cmake -DFORCE_CUDA=1 -DCMAKE_CXX_COMPILER=${{ matrix.compiler }} ..
          if: matrix.os == 'windows-latest'
            cmake -DFORCE_CUDA=1 ..
          cmake --build . --config Release 
