name: Distributed CPU Build And Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build-and-test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        compiler: [g++, clang++]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Prep Build
        run: |
          echo "CXX=${{ matrix.compiler }}" >> $GITHUB_ENV
          if [ "${{ matrix.compiler }}" = "g++" ]; then
            echo "CC=gcc" >> $GITHUB_ENV
          elif [ "${{ matrix.compiler }}" = "clang++" ]; then
            echo "CC=clang" >> $GITHUB_ENV
          fi
            
      - name: Build SCAMP Distributed
        shell: bash
        run: |
          set -e
          cd $GITHUB_WORKSPACE
          mkdir build && cd build
          cmake -DBUILD_CLIENT_SERVER=1 ..
          cmake --build . --config Release --parallel 2

      - name: Distributed Tests SCAMP
        shell: bash
        run: |
          set -e
          python3 -m pip install numpy pandas tqdm
          cd $GITHUB_WORKSPACE/test
          ../build/kubernetes/SCAMPserver &
          ../build/kubernetes/SCAMPclient &
          sleep 10
          ./run_tests.sh ../build/kubernetes/SCAMP_distributed /dev/null 
          python3 ./run_tests.py --executable ../build/kubernetes/SCAMP_distributed --window_sizes 100 --extra_args "--no_gpu --num_cpu_workers=1 --distributed_tile_size=1500"
