name: Run clang-format Linter

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: DoozyX/clang-format-lint-action@v0.13
      with:
        source: '.'
        exclude: './lib'
        extensions: 'h,cpp,c,cu'
        clangFormatVersion: 6
        inplace: True
    - uses: EndBug/add-and-commit@v7.5.0
      with:
        default_author: github_actions
        committer_name: GitHub Actions
        committer_email: actions@github.com
        message: 'Committing clang-format changes'
