name: Pyscamp Build And Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build-and-test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Build pyscamp
        shell: bash
        run: |
          set -e
          cd $GITHUB_WORKSPACE
          python3 -m pip install .
          python3 -m pip install numpy

      - name: pyscamp Test
        shell: bash
        run: |
          set -e
          cd $GITHUB_WORKSPACE/test
          python3 test_pyscamp.py
