name: Standard Build And Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build-and-test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        compiler: [g++, clang++, cl]
        exclude:
          - os: ubuntu-latest
            compiler: cl
          - os: macos-latest
            compiler: cl
          - os: windows-latest
            compiler: g++
          - os: windows-latest
            compiler: clang++

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'

      - name: Prep Build
        run: echo "CXX=${{ matrix.compiler }}" >> $GITHUB_ENV
          
      - name: Build SCAMP
        shell: bash
        run: |
          set -e
          cd $GITHUB_WORKSPACE
          mkdir build && cd build
          cmake ..
          cmake --build . --config Release 
          if [ -f "./Release/SCAMP.exe" ]; then
            cp ./Release/SCAMP.exe ./SCAMP
          fi

      - name: Basic Tests SCAMP
        shell: bash
        run: |
          set -e
          cd $GITHUB_WORKSPACE/test
          ./run_tests.sh ../build/SCAMP /dev/null "--no_gpu=true --num_cpu_workers=2"
          
      - name: Extended Tests SCAMP
        shell: bash
        run: |
          set -e
          python3 -m pip install numpy pandas tqdm
          cd $GITHUB_WORKSPACE/test
          python3 ./run_tests.py --executable "../build/SCAMP" --extra_args "--no_gpu --num_cpu_workers=2"
               
