# This is a basic workflow to help you get started with Actions

name: Ubuntu Cuda Build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - uses: Jimver/cuda-toolkit@v0.2.5
        id: cuda-toolkit
        with:
          cuda: '11.5.1'

      # Runs a single command using the runners shell
      - name: Build SCAMP
        run: |
          set -e
          cd $GITHUB_WORKSPACE
          mkdir build && cd build
          cmake -D FORCE_CUDA=1 -D CMAKE_CXX_COMPILER=clang++ ..
          make -j2
          rm -rf *
          cmake -D FORCE_CUDA=1 -D CMAKE_CXX_COMPILER=g++ ..
          make -j2
          rm -rf *
          cmake -D FORCE_CUDA=1 ..
          make -j2
          rm -rf *
          cmake -DFORCE_CUDA=1 -DCMAKE_CXX_COMPILER=g++ -DBUILD_CLIENT_SERVER=1 ..
          make -j2
